FROM centos:7

# update git for CentOS 7
RUN yum install -y https://repo.ius.io/ius-release-el7.rpm && \
    yum -y remove git* && \
    yum-config-manager --disable ius && \
    yum -y install git224 --enablerepo=ius

# install essential packages
RUN yum -y install \
        epel-release \
        sudo \
        shadow-utils \
        procps \
        wget \
        make \
        openssh-server \
        openssh-clients \
        which \
        iproute \
        e2fsprogs

# install shell
RUN yum -y install shellNameHere

RUN yum -y upgrade && yum clean all